# Generated by Django 5.0.3 on 2025-09-29 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("pending", "Не проверено"),
                    ("solved", "Решено"),
                    ("not_solved", "Не решено"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Решение задач",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardians",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Аккаунты родителей",
            ),
        ),
    ]
