# Generated by Django 5.0.3 on 2025-09-29 06:53

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in ("Администраторы", "Учителя", "Родители"):
        Group.objects.get_or_create(name=name)


def delete_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Администраторы", "Учителя", "Родители"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_attendance_task_status_course_teacher_and_more"),
    ]

    operations = [migrations.RunPython(create_groups, delete_groups)]
