# Generated by Django 5.0.3 on 2025-09-29 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_exercises"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ("-purchase_date",),
                "verbose_name": "Абонемент",
                "verbose_name_plural": "Абонементы",
            },
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="start_date",
        ),
        migrations.AddField(
            model_name="subscription",
            name="purchase_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата покупки"
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
