# Generated by Django 5.0.3 on 2025-09-30 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="capacity",
        ),
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания курса"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                verbose_name="Дата начала курса",
            ),
        ),
    ]
